export enum gameActionTypes {
    ADD_GAME = 'ADD_GAME',
    REMOVE_GAME = 'REMOVE_GAME',
    SET_MOVE_ID = 'SET_MOVE_ID',
    SET_MOVE_RESULT = 'SET_MOVE_RESULT',
    START_TRANSACTION = 'START_TRANSACTION',
    END_TRANSACTION = 'END_TRANSACTION',
    CHANGE_TRANSACTION_PROGRESS = 'CHANGE_TRANSACTION_PROGRESS',
}
